### ISSUE TITLE
エラーのご報告

### ISSUE THREAD

**Issue by takahashimakoto** [ArtemisJP/RPGMZ-ARTM_TMEventItemExMz#2]
このプラグインを使わせていただきゲームを制作しているのですが、
エラーが出て動かなくなってしまいます。

使わせていただいたプラグインが原因かは分からず大変恐れ入りますが、
ご報告だけさせていただきます。

**Comment by ArtemisJP** [comment]
お返事が遅れて申し訳ありません。
お手数ですが、エラー内容の貼り付けと、ご使用されている他のプライグイン名を教えていただけますでしょうか。

**Comment by takahashimakoto** [comment]
ご返信いただきありがとうございます。
ARTM_TMEventItemExMz.jsを使わせていただいており、以下のようなエラーが出ております。

━━━━━━━━━━━━━━━
TypeError: Cannot read properties of undefined (reading 'height')
    rmmz_managers.js:39 
    at Window_EventItem.placeCancelButton (ARTM_TMEventItemExMz.js:5:832)
    at Window_EventItem.start (rmmz_windows.js:100:778)
    at Window_EventItem.start (ARTM_TMEventItemExMz.js:2:201)
    at Window_Message.startInput (rmmz_windows.js:113:285)
    at Window_Message.startInput (**************.js:13:35)
    at Window_Message.update (rmmz_windows.js:102:1577)
    at WindowLayer.update (rmmz_core.js:101:278)
    at Scene_Base.updateChildren (rmmz_scenes.js:3:129)
    at Scene_Base.update (rmmz_scenes.js:2:709)
    at Scene_Map.update (rmmz_scenes.js:14:315)
━━━━━━━━━━━━━━━

**Comment by ArtemisJP** [comment]
お返事が遅れて大変申し訳ございません。
お時間いただく形となりますが、調査をし対応予定です
